baseURL = "https://shelbyspees.com"
languageCode = "en-us"
title = "shelby spees"
theme = "noteworthy"

paginate = 6 # Set the number of posts to show before overflowing to the next page.

[permalinks]
  posts = "/:year/:month/:day/:title/"

[[menu.main]]
  identifier = "posts"
  name = "posts"
  url = "/posts/"
  weight = -1

[[menu.main]]
  identifier = "threads"
  name = "threads"
  url = "/threads/"
  weight = 2

  [[menu.main]]
  identifier = "nova"
  name = "dog"
  url = "/nova/"
  weight = 3

[[menu.main]]
  identifier = "notes"
  name = "notes"
  url = "https://notes.shelbyspees.com/"
  post = "&nbsp;&nbsp;<i class='fa fa-external-link' aria-hidden='true' title='External link'></i><span class='sr-only'>External link</span>"
  weight = 4

[[menu.main]]
  identifier = "speaking"
  name = "speaking"
  post = "&nbsp;&nbsp;<i class='fa fa-external-link' aria-hidden='true' title='External link'></i><span class='sr-only'>External link</span>"
  url = "https://speaking.shelbyspees.com/"
  weight = 5

[params]
  showReadMore = true
  mainSections = ["posts"]
  # Social media
  twitter = "https://twitter.com/shelbyspees/"
  linkedin = "https://linkedin.com/in/shelbyspees/"
  github = "https://github.com/shelbyspees/"
  twitch = "https://twitch.tv/shelbyspees/"
  icon = "nova-ears.png"

[markup.goldmark.renderer]
  unsafe = true
