baseURL = "http://shelbyspees.com/"
languageCode = "en-us"
title = "Shelby Spees"
theme = "noteworthy"

paginate = 4 # Set the number of posts to show before overflowing to the next page.

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/"
  weight = -1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[params]
  showReadMore = true
  # Social media
  twitter = "http://twitter.com/shelbyspees"
  linkedin = "http://linkedin.com/in/shelbyspees"
  github = "http://github.com/shelbyspees"
