baseURL = "https://shelbyspees.com/"
languageCode = "en-us"
title = "Shelby Spees"
theme = "noteworthy"

paginate = 4 # Set the number of posts to show before overflowing to the next page.

[permalinks]
  posts = "/:year/:month/:day/:title/"

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = -1

[[menu.main]]
  identifier = "talks"
  name = "Talks"
  url = "/talks/"
  weight = 1

[[menu.main]]
  identifier = "nova"
  name = "Nova"
  url = "/nova/"
  weight = 2

[params]
  showReadMore = true
  # Social media
  twitter = "http://twitter.com/shelbyspees/"
  linkedin = "http://linkedin.com/in/shelbyspees/"
  github = "http://github.com/shelbyspees/"
  twitch = "http://twitch.tv/shelbyspees/"
  icon = "nova-ears.png"

[markup.goldmark.renderer]
  unsafe = true
