baseURL = "https://spees.dev"
languageCode = "en-us"
theme = "hello-friend-ng"
title = "Shelby Spees"

paginate = 15
enableGitInfo = true
googleAnalytics = "UA-178718117-1"

[permalinks]
  posts = "/:slug/"
  # posts = "/:year/:month/:day/:slug/"

[author]
  name = "Shelby Spees"

[taxonomies]
  tags = "tags"
  categories = "categories"
  series = "series"

[params]
  defaultTheme = "light"
  mainSections = ["posts"]
  showReadMore = true
  gitUrl = "https://github.com/shelbyspees/website/commit/"
  description = "Shelby Spees is a site reliability engineer and DevOps advocate dedicated to improving access and equity in tech."
  homeSubtitle = "site reliability engineer · devops advocate · dog mom"
  images = ["https://ik.imagekit.io/spees/heart_2r5Z23Y4ny0.png?updatedAt=1633245483713&ik-s=5ae229e7d90f13a0d188e7e766997c0acd09f858"]
  footerSocial = true

[params.logo]
  logoText = "shelby spees"
  logoCursorDisabled = true

# [params.portrait]
#   path = "/shelby_profile.jpg"
  # alt = "Shelby Spees headshot"

# Social icons
[[params.social]]
  name = "twitter"
  url = "https://twitter.com/shelbyspees"

[[params.social]]
  name = "github"
  url = "https://github.com/shelbyspees"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/shelbyspees"

[[params.social]]
  name = "rss"
  url = "/posts/index.xml"

# Top nav menu
[[menu.main]]
  identifier = "posts"
  name = "posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 3

[[menu.main]]
  identifier = "nova"
  name = "dog ↗"
  url = "https://nova.spees.dog"
  weight = 5

[markup.goldmark.renderer]
  unsafe = true
