baseURL = "https://shelbyspees.com"
languageCode = "en-us"
theme = "hello-friend-ng"
title = "shelby spees"

paginate = 15
enableGitInfo = true
googleAnalytics = "UA-178718117-1"

[permalinks]
  posts = "/:year/:month/:day/:title/"


[author]
  name = "shelby spees"

[params]
  defaultTheme = "light"
  homeSubtitle = "developer advocate, dog mom, etc."
  mainSections = ["posts"]
  showReadMore = true
  gitUrl = "https://github.com/shelbyspees/website/commit/"
  description = "shelby spees: developer advocate, dog mom, etc."
  images = ["/twitter-card-large.png"]

[params.logo]
  path = "/nova-ears.svg"
  logoText = "shelbyspees.com"

[params.portrait]
  path = "/shelby_profile.jpg"
  alt = "Shelby Spees headshot"

# Social icons
[[params.social]]
  name = "twitter"
  url = "https://twitter.com/shelbyspees"

[[params.social]]
  name = "github"
  url = "https://github.com/shelbyspees"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/shelbyspees"

[[params.social]]
  name = "notion"
  url = "https://notes.shelbyspees.com"

[[params.social]]
  name = "rss"
  url = "/posts/index.xml"

# /links page (see layouts/_default/links.html)
[[params.links]]
  name = "twitter"
  url = "https://twitter.com/shelbyspees"

[[params.links]]
  name = "github"
  url = "https://github.com/shelbyspees"

[[params.links]]
  name = "linkedin"
  url = "https://linkedin.com/in/shelbyspees"

[[params.links]]
  name = "speaker portfolio"
  url = "https://speaking.shelbyspees.com"

[[params.links]]
  name = "observability office hours"
  url = "https://honeycomb.io/meet/shelby"

[[params.links]]
  name = "work email"
  url = "mailto:shelby@honeycomb.io"

# Top nav menu
[[menu.main]]
  identifier = "posts"
  name = "posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  identifier = "nova"
  name = "dog"
  url = "/nova/"
  weight = 3

[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 4

[[menu.main]]
  identifier = "contact"
  name = "contact"
  url = "/contact/"
  weight = 5

[markup.goldmark.renderer]
  unsafe = true
