baseURL = "https://shelbyspees.com"
languageCode = "en-us"
theme = "hello-friend-ng"
title = "shelby spees"

paginate = 15
enableGitInfo = true
googleAnalytics = "UA-178718117-1"

[permalinks]
  posts = "/:year/:month/:day/:title/"


[author]
  name = "Shelby Spees"

[params]
  defaultTheme = "light"
  homeSubtitle = "developer advocate, dog mom, etc."
  mainSections = ["posts"]
  showReadMore = true
  gitUrl = "https://github.com/shelbyspees/website/commit/"
  description = "shelby spees: developer advocate, dog mom, etc."
  images = ["/nova-ears.png"]

[params.logo]
  logoHomeLink = "/"
  logoText = "shelbyspees.com"
  logoCursorColor = "#63BDA2"

[params.portrait]
  path = "/nova-ears.png"
  alt = "Nova ears logo"
  maxWidth = "600px"

# Social icons
[[params.social]]
  name = "twitter"
  url = "https://twitter.com/shelbyspees"

[[params.social]]
  name = "twitch"
  url = "https://www.twitch.com/shelbyspees"

[[params.social]]
  name = "github"
  url = "https://github.com/shelbyspees"

[[params.social]]
  name = "dev"
  url = "https://dev.to/shelbyspees"

[[params.social]]
  name = "notion"
  url = "https://notes.shelbyspees.com"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/shelbyspees"

[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = -1

[[menu.main]]
  identifier = "posts"
  name = "posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  identifier = "nova"
  name = "dog"
  url = "/nova/"
  weight = 3

[markup.goldmark.renderer]
  unsafe = true
