baseURL = "https://shelbyspees.com/"
languageCode = "en-us"
title = "Shelby Spees"
theme = "noteworthy"

paginate = 4 # Set the number of posts to show before overflowing to the next page.

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = -1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 3

[params]
  description = "Developer Advocate, Software Engineer, and Dog Mom"
  showReadMore = true
  # Social media
  twitter = "http://twitter.com/shelbyspees"
  linkedin = "http://linkedin.com/in/shelbyspees"
  github = "http://github.com/shelbyspees"

[markup.goldmark.renderer]
  unsafe = true
