command = "git submodule update --init --recursive --depth=1 && hugo --minify"

[build.environment]
HUGO_VERSION = "0.72.0"

[context.branch-deploy.environment]
  HUGO_BASEURL = "/"

[[redirects]]
  from = "/threads"
  to = "/categories/twitter-threads"
  status = 301
  force = true

[[redirects]]
  from = "https://nova.spees.dev/*"
  to = "https://shelbyspees.com/nova/:splat"
  status = 200
  force = true
