command = "git submodule update --init --recursive --depth=1 && hugo --minify"

[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

	[plugins.inputs]
	# If it should show more verbose logs (optional, default = true)
	debug = true

[build.environment]
HUGO_VERSION = "0.72.0"

[context.branch-deploy.environment]
  HUGO_BASEURL = "/"

[[redirects]]
  from = "/threads"
  to = "/categories/twitter-threads"
  status = 301
  force = true

[[redirects]]
  from = "https://nova.spees.dev/*"
  to = "https://spees.dev/nova/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://notes.spees.dev/*"
  to = "https://notes.shelbyspees.com/:splat"
  status = 301
  force = true
